name: Generate GitHub Profile Stats SVG

on:
  schedule:
    - cron: '0 */12 * * *' # Automatically updates every 12 hours
  workflow_dispatch: # Allows you to manually trigger it anytime

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-stats-svg

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: cronomx
          THEME: tokyo_night

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update profile stats SVG charts"
          git push
